[general]

import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[window]

option_as_alt = "Both"

[font.normal]

family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]

family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]

family = "FiraCode Nerd Font"
style = "Italic"

[terminal.shell]

program = "/bin/bash"
args = ["-l", "-c", "zellij attach --index 0 || zellij"]

[env]

TERM = "xterm-256color"
XDG_CONFIG_HOME = "/Users/rowan/.config"